services:
  neteasemusic-scrobbler:
    container_name: neteasemusic-scrobbler
    build:
      context: .
    # ports:
    # - 80:80
    environment:
    # - IS_FASTAPI_DEBUG=true # Set to true to enable docs, redocs, openapi.json
    - MALOJA_API_URL=${MALOJA_API_URL}
    - MALOJA_API_TOKEN=${MALOJA_API_TOKEN}
    - API_KEY=${API_KEY}
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neteasemusic-scrobbler.rule=Host(`${SCROBBLER_DOMAIN}`)"
      - "traefik.http.routers.neteasemusic-scrobbler.service=neteasemusic-scrobbler-service"
      - "traefik.http.services.neteasemusic-scrobbler-service.loadbalancer.server.port=80"
      - "traefik.http.routers.neteasemusic-scrobbler.tls=true"
      - "traefik.http.routers.neteasemusic-scrobbler.tls.certresolver=le"
      - "traefik.http.routers.neteasemusic-scrobbler.middlewares=cors@docker"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"

networks:
  public:
    external: true
