services:
  neteasemusic-scrobbler:
    container_name: neteasemusic-scrobbler
    build:
      context: .
    ports:
    - 8888:80
    environment:
    # - IS_FASTAPI_DEBUG=true # Set to true to enable docs, redocs, openapi.json
    - MALOJA_API_URL=${MALOJA_API_URL}
    - MALOJA_API_TOKEN=${MALOJA_API_TOKEN}
    - API_KEY=${API_KEY}
